### ISSUE TITLE
New project fails with SyntaxError

### ISSUE THREAD

**Issue by aonemd** [nativescript-vue/vue-cli-template#119]
### Version
Vue version: 3.2.1

### Reproduction link
[https://github.com/aonemd/new_project](https://github.com/aonemd/new_project)
### Platform and OS info
OS: ArchLinux, Phone OS: Android 7.0, NativeScript: 5.1.0

### Steps to reproduce
- yarn add global @vue/cli @vue/cli-init
- vue init nativescript-vue/vue-cli-template new_project
- cd new_project
- yarn install
- tns preview

### What is expected?
The app should open on my device

### What is actually happening?
```
LOG from device PhoneName: com.tns.NativeScriptException:

Cannot compile /data/data/org.nativescript.preview/files/app/main.js

SyntaxError: Unexpected identifier
File: "file:///data/data/org.nativescript.preview/files/app/main.js, line: 1

StackTrace:
        Frame: function:'require', file:'', line: 1, column: 266


SyntaxError: Unexpected identifier
File: "<unknown>, line: 1, column: 265

StackTrace:
        Frame: function:'require', file:'', line: 1, column: 266


        at com.tns.Runtime.runModule(Native Method)
        at com.tns.Runtime.runModule(Runtime.java:553)
        at com.tns.Runtime.run(Runtime.java:545)
        at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentati
        at android.app.ActivityThread.handleBindApplication(ActivityThread.j
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:16
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6375)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(Zygote
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
```

**Comment by rigor789** [comment]
Missing `--bundle` flag in the `tns preview` command. Without it, it tries to run .vue files at runtime rather than compiling them with webpack.

**Comment by aonemd** [comment]
Thanks a lot. I think using `--bundle` works. I got another error. Will report it as well. 
By the way, shouldn't this be added to the README.md?

**Comment by rigor789** [comment]
The bundle flag is in the README for run/debug/build commands, but the preview command is not mentioned. Would you mind opening a PR and adding the preview command usage?

**Comment by aonemd** [comment]
Sure!
