### ISSUE TITLE
Cannot run the NativeScript Vue app.

### ISSUE THREAD

**Issue by rigor789** [nativescript-vue/vue-cli-template#30]
_From @Himujjal on March 26, 2018 20:0_

I simply followed the official documentation and then run the following app in my emulator. 
I used the following commands:
```
npm install -g @vue/cli @vue/cli-init
vue init nativescript-vue/vue-cli-template yoyo
cd yoyo
npm install
```
The app is showing an error message. It gets installed in the emulator though: 

```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "D:\Coding_Files\nativescript\nativescript-vue\tutorial\yoyo\src\main.js", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:530)
    com.tns.Runtime.run(Runtime.java:522)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 546
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 511
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 520
	Frame: function:'require', file:'', line: 1, column: 266


Error: com.tns.NativeScriptException: Failed to find module: "D:\Coding_Files\nativescript\nativescript-vue\tutorial\yoyo\src\main.js", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:530)
    com.tns.Runtime.run(Runtime.java:522)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 546
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 511
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 520
	Frame: function:'require', file:'', line: 1, column: 266


	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4710)
	at android.app.ActivityThread.-wrap1(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: com.tns.NativeScriptException: 

Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "D:\Coding_Files\nativescript\nativescript-vue\tutorial\yoyo\src\main.js", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:530)
    com.tns.Runtime.run(Runtime.java:522)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 546
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 511
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 520
	Frame: function:'require', file:'', line: 1, column: 266


Error: com.tns.NativeScriptException: Failed to find module: "D:\Coding_Files\nativescript\nativescript-vue\tutorial\yoyo\src\main.js", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:530)
    com.tns.Runtime.run(Runtime.java:522)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
    android.app.ActivityThread.-wrap1(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:148)
    android.app.ActivityThread.main(ActivityThread.java:5417)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 546
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 511
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 520
	Frame: function:'require', file:'', line: 1, column: 266


	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:530)
	at com.tns.Runtime.run(Runtime.java:522)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
	... 8 more
```

_Copied from original issue: nativescript-vue/nativescript-vue#162_

**Comment by Himujjal** [comment]
Any updates on this issue. I am able to run the app using `tns create first-app2 --template nativescript-vue-template` command but not this.

**Comment by rigor789** [comment]
Are you on windows by any chance?

**Comment by Himujjal** [comment]
Yes. I am on Windows 10. I have the android studio installed and I am running an emulator with Android 6.0 (Marshmallow) on it (Used this version for React Native). 

The app gets built and this error code appears while the app loads in the emulator

**Comment by rigor789** [comment]
Okay, then it looks like it's the same issue as this one: https://github.com/nativescript-vue/nativescript-vue-externals/issues/1

**Comment by jefrydco** [comment]
@rigor789 I'm using Linux and I got the same problem,

**Comment by derAndreas** [comment]
@jefrydco Can you please check if you have any special or uppercase chars in your project path?

My project was located in `/home/user/Development/My-Projects/nativescript-tests/demo` and was not working. Then (after some hours! of testing) I tried in `/tmp` and it was working!

Some tests later I discoverd that the template is trying to prevent us from using uppercase letters when initing:
```
/tmp $ vue init nativescript-vue/vue-cli-template YoYo

? Project name (YoYo) 
>> Sorry, name can no longer contain capital letters.
```
But if you path already contains an uppercase char, the template init will not check that :(

MAYBE this is a solution, but I am not sure. Could be also a combination of uppercase and dashes (-) in the path?

@rigor789 Could you also please check if uppercase-in-pathname  is the case or something else is wrong?

P.S.: This is my first try with nativescript and this issue was eating hours. Now I just want to play around and not further debug ;) If you need more informations, I will try to provide them.

For versions and os info:
- LinuxMint 18.3
- node 8.10.0
- npm 5.8.0
- nativescript: First and fresh install, so current version numbers that NPM gave me
- android-studio AI-173.4697961

Also to note the commands I used, which are all from the quickstart tutorial: 
> https://nativescript-vue.org/en/docs/getting-started/quick-start/

Regards
Andreas

**Comment by nordicbackup** [comment]
Andreas, was having the same problem on windows 10 and testing your theory I switched to the  command terminal and copied the path from a window (so that it retained the capitalization) and it worked.

THANKS

**Comment by netchampfaris** [comment]
I am on macOS 10.13.2, it is as @derAndreas says, I created the project in my `~/Projects` folder, didn't work. Then, I created it in `/tmp` and it worked.

**Comment by rigor789** [comment]
Can you try again using `nativescript-vue-externals@0.2.0` which fixes a lot of the existing path issues?

Closing the issue, but if it happens with the latest version of  `nativescript-vue-externals` feel free to open a new issue with additional details.
