### ISSUE TITLE
--env  Not sure what you mean there

### ISSUE THREAD

**Issue by gustawdaniel** [nativescript-vue/vue-cli-template#72]
### Version
N/A

### Reproduction link
[http://please-do-not-require-any-link.com/i_described_anything](http://please-do-not-require-any-link.com/i_described_anything)
### Platform and OS info
Ubuntu 18

### Steps to reproduce
# Scaffold project

```
npm install -g vue-cli
vue init nativescript-vue/vue-cli-template sms_api
cd sms_api
```

# Install dependencies

    npm install

# Build, watch for changes and debug the application

    npm run watch

### What is expected?
I was expected qr code to scan

### What is actually happening?
```
> sms_api@1.0.0 watch /home/daniel/pro/sms_api
> webpack --watch --env.tnsAction run

info: Copying NativeScript plugins to template dependencies...
info: Preparing NativeScript application from template...
npm WARN sms_api@ No repository field.

info: Bundling application for android...
info: Bundling application for ios...

Webpack is watching the files…

Executing post-build scripts
info: Running NativeScript application...
error: uncaughtException: 127 date=Sat Jul 28 2018 10:48:17 GMT 0200 (CEST), pid=5978, uid=1000, gid=1000, cwd=/home/daniel/pro/sms_api, execPath=/home/daniel/.nvm/versions/node/v8.11.1/bin/node, version=v8.11.1, argv=[/home/daniel/.nvm/versions/node/v8.11.1/bin/node, /home/daniel/pro/sms_api/node_modules/.bin/webpack, --watch, --env.tnsAction, run], rss=215699456, heapTotal=166645760, heapUsed=96710616, external=1657998, loadavg=[1.56640625, 1.3330078125, 1.205078125], uptime=2710, trace=[], stack=undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sms_api@1.0.0 watch: `webpack --watch --env.tnsAction run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sms_api@1.0.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daniel/.npm/_logs/2018-07-28T08_48_18_026Z-debug.log
```

---
File with full log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/daniel/.nvm/versions/node/v8.11.1/bin/node',
1 verbose cli   '/home/daniel/.nvm/versions/node/v8.11.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'watch' ]
2 info using npm@6.2.0
3 info using node@v8.11.1
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle sms_api@1.0.0~prewatch: sms_api@1.0.0
6 info lifecycle sms_api@1.0.0~watch: sms_api@1.0.0
7 verbose lifecycle sms_api@1.0.0~watch: unsafe-perm in lifecycle true
8 verbose lifecycle sms_api@1.0.0~watch: PATH: /home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/daniel/pro/sms_api/node_modules/.bin:/home/daniel/.yarn/bin:/home/daniel/.config/yarn/global/node_modules/.bin:/home/daniel/.rakudobrew/bin:/home/daniel/perl5/bin:/home/daniel/.nvm/versions/node/v8.11.1/bin:/home/daniel/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle sms_api@1.0.0~watch: CWD: /home/daniel/pro/sms_api
10 silly lifecycle sms_api@1.0.0~watch: Args: [ '-c', 'webpack --watch --env.tnsAction run' ]
11 silly lifecycle sms_api@1.0.0~watch: Returned: code: 1  signal: null
12 info lifecycle sms_api@1.0.0~watch: Failed to exec watch script
13 verbose stack Error: sms_api@1.0.0 watch: `webpack --watch --env.tnsAction run`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid sms_api@1.0.0
15 verbose cwd /home/daniel/pro/sms_api
16 verbose Linux 4.15.0-29-generic
17 verbose argv "/home/daniel/.nvm/versions/node/v8.11.1/bin/node" "/home/daniel/.nvm/versions/node/v8.11.1/bin/npm" "run" "watch"
18 verbose node v8.11.1
19 verbose npm  v6.2.0
20 error code ELIFECYCLE
21 error errno 1
22 error sms_api@1.0.0 watch: `webpack --watch --env.tnsAction run`
22 error Exit status 1
23 error Failed at the sms_api@1.0.0 watch script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

When I type:

    webpack --watch --env.tnsAction debug

I can see

```
✖ ｢webpack｣: Flags were specified that were not recognized:

  --env  Not sure what you mean there

Please check the command executed.
```

**Comment by gustawdaniel** [comment]
I updated wepack from `0.4.1` to `4.16.3` and now have other error:

Command:

```
npm run watch
```

Result:

```
> @ watch /home/daniel/pro/sms_api
> webpack --watch --env.tnsAction run

info: Copying NativeScript plugins to template dependencies...
info: Preparing NativeScript application from template...
npm WARN tns-template-vue@ No repository field.

info: Bundling application for android...
info: Bundling application for ios...

Webpack is watching the files…

Executing post-build scripts
info: Running NativeScript application...
Searching for devices...
error: uncaughtException: 127 date=Sat Jul 28 2018 11:37:21 GMT+0200 (CEST), pid=13138, uid=1000, gid=1000, cwd=/home/daniel/pro/sms_api, execPath=/home/daniel/.nvm/versions/node/v8.11.1/bin/node, version=v8.11.1, argv=[/home/daniel/.nvm/versions/node/v8.11.1/bin/node, /home/daniel/pro/sms_api/node_modules/.bin/webpack, --watch, --env.tnsAction, run], rss=194179072, heapTotal=156176384, heapUsed=92787304, external=1892766, loadavg=[1.58154296875, 1.70458984375, 1.81787109375], uptime=5654, trace=[], stack=undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ watch: `webpack --watch --env.tnsAction run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daniel/.npm/_logs/2018-07-28T09_37_21_736Z-debug.log
```

Command:

```
webpack --watch --env.tnsAction run
```

Result:

```
info: Copying NativeScript plugins to template dependencies...
info: Preparing NativeScript application from template...
npm WARN tns-template-vue@ No repository field.

info: Bundling application for android...
info: Bundling application for ios...

webpack is watching the files…

(node:13303) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(node:13303) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
(node:13303) DeprecationWarning: webpack: Using compiler.resolvers.normal is deprecated.
Use compiler.resolverFactory.plugin("resolver normal", resolver => {
  resolver.apply(/* … */);
}); instead.
(node:13303) DeprecationWarning: webpack: Using compiler.resolvers.normal is deprecated.
Use compiler.resolverFactory.plugin("resolver normal", resolver => {
  resolver.apply(/* … */);
}); instead.
(node:13303) DeprecationWarning: Compilation.moduleTemplate: Use Compilation.moduleTemplates.javascript instead
TypeError: dep.getResourceIdentifier is not a function
    at addDependency (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/webpack/lib/Compilation.js:665:30)
    at iterationOfArrayCallback (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/webpack/lib/Compilation.js:186:3)
    at addDependenciesBlock (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/webpack/lib/Compilation.js:687:5)
    at Compilation.processModuleDependencies (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/webpack/lib/Compilation.js:698:4)
    at afterBuild (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/webpack/lib/Compilation.js:830:15)
    at buildModule.err (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/webpack/lib/Compilation.js:874:11)
    at callback (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/webpack/lib/Compilation.js:611:5)
    at module.build.error (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/webpack/lib/Compilation.js:651:12)
    at handleParseResult (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/webpack/lib/NormalModule.js:441:12)
    at doBuild.err (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/webpack/lib/NormalModule.js:463:6)
    at runLoaders (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/webpack/lib/NormalModule.js:327:12)
    at /home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:370:3
    at iterateNormalLoaders (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:211:10)
    at Array.<anonymous> (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/webpack/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

Command:

```
cat /home/daniel/.npm/_logs/2018-07-28T09_37_21_736Z-debug.log
```

Result:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/daniel/.nvm/versions/node/v8.11.1/bin/node',
1 verbose cli   '/home/daniel/.nvm/versions/node/v8.11.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'watch' ]
2 info using npm@6.2.0
3 info using node@v8.11.1
4 verbose run-script [ 'prewatch', 'watch', 'postwatch' ]
5 info lifecycle @~prewatch: @
6 info lifecycle @~watch: @
7 verbose lifecycle @~watch: unsafe-perm in lifecycle true
8 verbose lifecycle @~watch: PATH: /home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/daniel/pro/sms_api/node_modules/.bin:/home/daniel/.yarn/bin:/home/daniel/.config/yarn/global/node_modules/.bin:/home/daniel/.rakudobrew/bin:/home/daniel/perl5/bin:/home/daniel/.yarn/bin:/home/daniel/.config/yarn/global/node_modules/.bin:/home/daniel/.rakudobrew/bin:/home/daniel/perl5/bin:/home/daniel/.yarn/bin:/home/daniel/.config/yarn/global/node_modules/.bin:/home/daniel/.rakudobrew/bin:/home/daniel/perl5/bin:/home/daniel/.nvm/versions/node/v8.11.1/bin:/home/daniel/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle @~watch: CWD: /home/daniel/pro/sms_api
10 silly lifecycle @~watch: Args: [ '-c', 'webpack --watch --env.tnsAction run' ]
11 silly lifecycle @~watch: Returned: code: 1  signal: null
12 info lifecycle @~watch: Failed to exec watch script
13 verbose stack Error: @ watch: `webpack --watch --env.tnsAction run`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/daniel/.nvm/versions/node/v8.11.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @
15 verbose cwd /home/daniel/pro/sms_api
16 verbose Linux 4.15.0-29-generic
17 verbose argv "/home/daniel/.nvm/versions/node/v8.11.1/bin/node" "/home/daniel/.nvm/versions/node/v8.11.1/bin/npm" "run" "watch"
18 verbose node v8.11.1
19 verbose npm  v6.2.0
20 error code ELIFECYCLE
21 error errno 1
22 error @ watch: `webpack --watch --env.tnsAction run`
22 error Exit status 1
23 error Failed at the @ watch script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by gustawdaniel** [comment]
Finally I installed webpack 3:

```
npm install --global webpack@3.11.0
```

It could be better documented.

Now I have only error:

```
info: Copying NativeScript plugins to template dependencies...
info: Preparing NativeScript application from template...
npm WARN tns-template-vue@ No repository field.

info: Bundling application for android...
info: Bundling application for ios...

Webpack is watching the files…

Executing post-build scripts
info: Running NativeScript application...
Searching for devices...
error: uncaughtException: 127 date=Sat Jul 28 2018 11:45:03 GMT+0200 (CEST), pid=13508, uid=1000, gid=1000, cwd=/home/daniel/pro/sms_api, execPath=/home/daniel/.nvm/versions/node/v8.11.1/bin/node, version=v8.11.1, argv=[/home/daniel/.nvm/versions/node/v8.11.1/bin/node, /home/daniel/.nvm/versions/node/v8.11.1/bin/webpack, --watch, --env.tnsAction, run], rss=192974848, heapTotal=158797824, heapUsed=92699264, external=1884574, loadavg=[1.39990234375, 1.1943359375, 1.48828125], uptime=6116, trace=[], stack=undefined
```

without problems with webpack

**Comment by rigor789** [comment]
You need to have your machine set up for native development, there is no QR code to scan, it will run on an emulator or a connected device after it has been built.

Can you make sure your computer is set up correctly? 
https://nativescript-vue.org/en/docs/getting-started/installation/

Installing webpack should not be necessary, as it is already a dependency of the template, and should be installed when `npm install` is run (no need for a global install like you did)

**Comment by gustawdaniel** [comment]
Ok. In react native probably it can be done by qr code. Anyway I done next step:

I installed SDKMAN and gradle using this tool:

    https://gradle.org/install/

Now when I type command:

```
    npm run watch:android
```

I can see

```
> @ watch:android /home/daniel/pro/sms_api
> npm run watch -- --env.android


> @ watch /home/daniel/pro/sms_api
> webpack --watch --env.tnsAction run "--env.android"

info: Copying NativeScript plugins to template dependencies...
info: Preparing NativeScript application from template...
npm WARN tns-template-vue@ No repository field.

info: Bundling application for android...

Webpack is watching the files…

Executing post-build scripts
info: Running NativeScript application...
Searching for devices...
# tns run android

==========

┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Usage                                                                                                                                 │ Synopsis                                                                                                                                                                                                                       │
│ Run on all connected devices and running emulators                                                                                    │ $ tns run android [--key-store-path <File Path> --key-store-password <Password> --key-store-alias <Name> --key-store-alias-password <Password>] [--release] [--justlaunch] [--bundle [<value>] [--env.*]]                      │
│ Run on a selected connected device or running emulator. Will start emulator with specified Device Identifier, if not already running. │ $ tns run android --device <Device ID> [--key-store-path <File Path> --key-store-password <Password> --key-store-alias <Name> --key-store-alias-password <Password>] [--release] [--justlaunch] [--bundle [<value>] [--env.*]] │
│ Start a default emulator if none are running, or run application on all connected emulators.                                          │ $ tns run android --emulator [--key-store-path <File Path> --key-store-password <Password> --key-store-alias <Name> --key-store-alias-password <Password>] [--release] [--justlaunch] [--bundle [<value>] [--env.*]]           │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

Runs your project on a connected Android device or in a native Android emulator, if configured. This is shorthand for prepare, build and deploy. While your app is running, prints the output from the application in the console and watches for changes in your code. Once a change is detected, it synchronizes the change with all selected devices and restarts/refreshes the application.

### Options

    * --device - Specifies a connected device/emulator to start and run the app.
    * --emulator - If set, runs the app in all available and configured android emulators. It will start an emulator if none are already running.
    * --justlaunch - If set, does not print the application output in the console.
    * --clean - If set, forces rebuilding the native application.
    * --no-watch - If set, changes in your code will not be reflected during the execution of this command.
    * --release - If set, produces a release build. Otherwise, produces a debug build. When set, you must also specify the --key-store-* options.
    * --key-store-path - Specifies the file path to the keystore file (P12) which you want to use to code sign your APK. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --key-store-password - Provides the password for the keystore file specified with --key-store-path. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --key-store-alias - Provides the alias for the keystore file specified with --key-store-path. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --key-store-alias-password - Provides the password for the alias specified with --key-store-alias-password. You can use the --key-store-* options along with --release to produce a signed release build. You need to specify all --key-store-* options.
    * --bundle - Specifies that a bundler (e.g. webpack) should be used if one is present. If no value is passed will default to webpack.
    * --env.* - Specifies additional flags that the bundler may process. May be passed multiple times. For example: --env.uglify --env.snapshot.
    * --syncAllFiles - Watches all production dependencies inside node_modules for changes. Triggers project rebuild if necessary!

### Attributes

    * <Device ID> is the index or Device Identifier of the target device as listed by $ tns device android --available-devices

error: uncaughtException: 127 date=Sat Jul 28 2018 12:09:42 GMT+0200 (CEST), pid=15546, uid=1000, gid=1000, cwd=/home/daniel/pro/sms_api, execPath=/home/daniel/.nvm/versions/node/v8.11.1/bin/node, version=v8.11.1, argv=[/home/daniel/.nvm/versions/node/v8.11.1/bin/node, /home/daniel/pro/sms_api/node_modules/.bin/webpack, --watch, --env.tnsAction, run, --env.android], rss=170737664, heapTotal=135303168, heapUsed=87361464, external=1355617, loadavg=[1.19384765625, 0.96630859375, 1.07861328125], uptime=7594, trace=[], stack=undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ watch: `webpack --watch --env.tnsAction run "--env.android"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daniel/.npm/_logs/2018-07-28T10_09_42_544Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ watch:android: `npm run watch -- --env.android`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ watch:android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/daniel/.npm/_logs/2018-07-28T10_09_42_563Z-debug.log
```

I will close this issue when I finally fix all errors.

**Comment by gustawdaniel** [comment]
I run also 

```
source "/home/daniel/.sdkman/bin/sdkman-init.sh"
```

And checked gradle version

```
gradle --version
```

And there are some warnings

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/daniel/.sdkman/candidates/gradle/4.9/lib/groovy-all-2.4.12.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

------------------------------------------------------------
Gradle 4.9
------------------------------------------------------------

Build time:   2018-07-16 08:14:03 UTC
Revision:     efcf8c1cf533b03c70f394f270f46a174c738efc

Kotlin DSL:   0.18.4
Kotlin:       1.2.41
Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          10.0.1 (Oracle Corporation 10.0.1+10-Ubuntu-3ubuntu1)
OS:           Linux 4.15.0-29-generic amd64
```

**Comment by gustawdaniel** [comment]
Discussion was finished in

> https://github.com/nativescript-vue/vue-cli-template/pull/71#pullrequestreview-141313032
